; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = nordicnrf52
board = adafruit_itsybitsy_nrf52840
framework = arduino
lib_deps =
	adafruit/Adafruit DotStar@^1.2.5
	Wire

[env:prod]
; production — default, no extra flags

[env:dev]
build_flags = -D DEV_BUILD -D CFG_DEBUG=1